# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-26 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_auto_20171226_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
